"""Ingress sync for customer custom domains (issue #202). Business-licensed — see LICENSE.

Cloud TLS story (docs/CLOUD.md):

- ``<slug>.<base_domain>`` rides the **wildcard** routers in the static cloud dynamic config
  (``infra/traefik/dynamic.cloud.yml``), terminated with the operator's Cloudflare **origin
  certificate** for ``*.<base_domain>`` — nothing per-org to do.
- A **custom CNAME domain** gets its certificate from **Let's Encrypt**: this module renders
  one Traefik file-provider fragment with a router pair (web + api paths) per *verified*
  domain, each carrying ``certResolver: letsencrypt``. Traefik watches the directory and
  issues/renews on its own. Unverified hosts get **no router and no cert** — the allow-list
  is exactly ``orgs.custom_domain WHERE custom_domain_verified_at IS NOT NULL``, so the box
  is never an open certificate factory (#202).

The fragment is rewritten (atomically) on every domain verify/clear, at API startup, and by
a daily worker cron against drift. When ``SCHAKL_CLOUD_INGRESS_DIR`` is unset the sync is a
no-op — dev and tests run without a shared volume.
"""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.models import Org, OrgStatus

logger = logging.getLogger(__name__)

_FRAGMENT_NAME = "custom-domains.yml"


def cname_target() -> str:
    """The DNS target a tenant points their custom-domain CNAME at."""
    return settings.cloud_cname_target or f"edge.{settings.base_domain}"


async def verified_domains(session: AsyncSession) -> list[str]:
    """Every routable custom domain. Suspended orgs keep their route (the login screen and
    the suspension message still render); soft-deleted orgs do not resolve, so they drop."""
    rows = await session.execute(
        select(Org.custom_domain)
        .where(
            Org.custom_domain.is_not(None),
            Org.custom_domain_verified_at.is_not(None),
            Org.status != OrgStatus.DELETED.value,
        )
        .order_by(Org.custom_domain.asc())
    )
    return [domain for (domain,) in rows]


def render_fragment(domains: list[str]) -> str:
    """The Traefik file-provider YAML for the verified custom domains.

    Emitted by hand (stable ordering, no YAML dependency): two routers per domain — the API
    path split mirrors ``infra/traefik/dynamic.yml`` — pointing at the services the static
    cloud config defines, both requesting a Let's Encrypt certificate.
    """
    if not domains:
        return "# schakl cloud: no verified custom domains.\nhttp: {}\n"
    lines: list[str] = [
        "# Generated by schakl (app/core/cloud/ingress.py) — do not edit by hand.",
        "http:",
        "  routers:",
    ]
    for index, domain in enumerate(domains):
        name = f"custdom-{index}"
        host = domain.replace("`", "")
        lines += [
            f"    {name}-api:",
            f"      rule: \"Host(`{host}`) && (PathPrefix(`/api/`) || PathPrefix(`/mcp`))\"",
            "      priority: 1000",
            "      service: schakl-api",
            "      entryPoints: [websecure]",
            "      tls:",
            "        certResolver: letsencrypt",
            f"    {name}-web:",
            f"      rule: \"Host(`{host}`)\"",
            "      service: schakl-web",
            "      entryPoints: [websecure]",
            "      tls:",
            "        certResolver: letsencrypt",
        ]
    return "\n".join(lines) + "\n"


def write_fragment(content: str) -> Path | None:
    """Atomic write into the shared directory Traefik watches; None when sync is off."""
    if not settings.cloud_ingress_dir:
        return None
    directory = Path(settings.cloud_ingress_dir)
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / _FRAGMENT_NAME
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".custom-domains.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.replace(tmp_path, target)
    except OSError:
        logger.exception("could not write ingress fragment to %s", target)
        Path(tmp_path).unlink(missing_ok=True)
        return None
    return target


async def sync_ingress(session: AsyncSession) -> Path | None:
    """Regenerate the custom-domain fragment from the database. Never raises into the
    caller's request — a broken ingress sync must not fail a domain verification."""
    try:
        domains = await verified_domains(session)
        return write_fragment(render_fragment(domains))
    except Exception:  # noqa: BLE001 — log-and-continue by contract
        logger.exception("ingress sync failed")
        return None
