"""Reading an uploaded table: CSV, TSV, a pasted block, or Excel (issue #77).

Split out of :mod:`app.core.impex.service` because parsing is where the **untrusted bytes**
are, and it is the one part of the engine that has to be defensive rather than merely correct.
Everything downstream — validation, upsert, the report — sees the same
``list[str]``-of-``list[str]`` whatever the source was, so a mapped import of an ``.xlsx`` and
of the equivalent CSV are the same code path.

Three rules the shape here exists to keep:

* **The API parses, not the browser** (Golden Rule 6). One hardening surface, and an MCP or
  API caller gets the same capability as the web app rather than a second, weaker path.
* **Every limit is checked before the work it bounds**, never after: the byte cap before
  decoding, the zip's *declared* sizes before decompressing, the column cap before building
  rows. A guard that runs after the allocation it was protecting is decoration.
* **Reject, never truncate.** A file one row over the cap is a 413. Silently importing the
  first 2000 rows of a 2500-row list is the worst possible outcome — it looks like it worked.
"""

from __future__ import annotations

import csv
import io
import zipfile
from dataclasses import dataclass
from datetime import date, datetime, time
from decimal import Decimal
from typing import Any

from app.errors import AppError

#: Synchronous import ceiling; row MAX+1 onward is a 413, never a silent truncation.
MAX_IMPORT_ROWS = 2000
#: Byte ceiling for an uploaded file — a 2000-row CSV is well under this.
MAX_IMPORT_BYTES = 5 * 1024 * 1024
#: Byte ceiling for a *pasted* block. Starlette's ``Request.form()`` caps a non-file part at
#: 1 MiB and would **truncate** beyond it, so a larger limit here could never be enforced —
#: the check would run on bytes that had already been cut. A 2000-row paste is ~200 KB.
MAX_PASTE_BYTES = 1024 * 1024
#: Column ceiling. ``ws.max_column`` is routinely 16 384 on a sheet that merely has stray
#: formatting, so this bounds the *populated* width, measured from the header row.
MAX_COLUMNS = 200

#: --- xlsx zip guards, all read from the central directory (no decompression) ------------ #
#: Total declared uncompressed size of every member.
MAX_XLSX_INFLATED_BYTES = 64 * 1024 * 1024
#: A worksheet compresses ~10:1; 200:1 is a bomb, not a spreadsheet.
MAX_XLSX_RATIO = 200
#: A real workbook has a handful of parts per sheet plus styles/strings.
MAX_XLSX_MEMBERS = 200

#: Tried in order. ``cp1252`` is what a Dutch Excel "CSV (gescheiden door lijstscheidingsteken)"
#: writes; ``latin-1`` decodes any byte at all and is the last resort, so a delimited file is
#: never rejected for its encoding — the wizard shows the detected encoding and the sample
#: cells, which is a far better check than a decode error the user cannot act on.
ENCODINGS = ("utf-8-sig", "cp1252", "latin-1")

#: Candidate delimiters, widest first for the tie-break. Tab is what a spreadsheet puts on the
#: clipboard, which is the whole point of the paste box.
DELIMITERS = ",;\t|"

_XLSX_MAGIC = b"PK\x03\x04"


@dataclass(frozen=True)
class ParsedTable:
    """One uploaded table, normalised to strings.

    ``header`` is empty when the caller said the file has none — the columns are then
    addressed purely by position, which is what the mapping step does anyway.
    """

    header: list[str]
    rows: list[list[str]]
    #: "csv" (any delimited text, including a paste) or "xlsx".
    source_format: str
    delimiter: str | None = None
    encoding: str | None = None
    sheet: str | None = None
    #: Every sheet in the workbook, so the wizard can offer a picker.
    sheets: tuple[str, ...] = ()
    #: Cells holding a formula the spreadsheet never calculated. Excel writes both the formula
    #: and its last cached result; a file generated by a library writes only the formula, and
    #: **the cached value is what we read** — so those cells arrive empty. Counted rather than
    #: guessed at, because a whole column silently blank is otherwise indistinguishable from a
    #: column the user meant to leave empty.
    uncalculated_formulas: int = 0

    @property
    def width(self) -> int:
        return max([len(self.header), *(len(row) for row in self.rows)], default=0)


def parse_source(
    raw: bytes,
    *,
    sheet: str | None = None,
    has_header: bool = True,
    pasted: bool = False,
) -> ParsedTable:
    """Bytes → a normalised table, or an :class:`AppError` naming what was wrong.

    The format is decided by the **content** (a zip magic number), never by the filename: an
    ``.xlsx`` that is really a CSV, and a ``.txt`` that is really a workbook, both happen, and
    a browser's declared content type is caller-supplied data like any other.
    """
    limit = MAX_PASTE_BYTES if pasted else MAX_IMPORT_BYTES
    if len(raw) > limit:
        raise AppError("file_too_large", "impex.errors.file_too_large", status_code=413)
    if not raw.strip():
        raise AppError("empty_file", "impex.errors.empty_file")

    table = (
        _parse_xlsx(raw, sheet=sheet)
        if raw[:4] == _XLSX_MAGIC
        else _parse_delimited(raw)
    )
    return _finish(table, has_header=has_header)


# --------------------------------------------------------------------------- #
# Delimited text
# --------------------------------------------------------------------------- #
def _decode(raw: bytes) -> tuple[str, str]:
    for encoding in ENCODINGS:
        try:
            return raw.decode(encoding), encoding
        except UnicodeDecodeError:
            continue
    # Unreachable: latin-1 maps every byte. Kept so a future edit to ENCODINGS that drops the
    # total codec fails loudly instead of falling through with an unbound name.
    raise AppError("invalid_file", "impex.errors.invalid_file")


def _sniff(sample: str) -> str:
    """Pick the delimiter. The sniffer first, then the honest fallback: count them.

    ``csv.Sniffer`` raises on a single-column file and on some perfectly ordinary pastes, and
    its exception carries no preference — falling back to a comma there would parse a
    tab-separated paste as one column, which is exactly the bug this stage exists to fix.
    """
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=DELIMITERS)
    except csv.Error:
        pass
    else:
        return dialect.delimiter
    first_line = sample.splitlines()[0] if sample.splitlines() else ""
    counts = {d: first_line.count(d) for d in DELIMITERS}
    best = max(counts, key=lambda d: counts[d])
    return best if counts[best] else ","


def _parse_delimited(raw: bytes) -> ParsedTable:
    text, encoding = _decode(raw)
    delimiter = _sniff(text[:4096])
    try:
        rows = [row for row in csv.reader(io.StringIO(text), delimiter=delimiter) if any(row)]
    except csv.Error as exc:
        raise AppError("invalid_file", "impex.errors.invalid_file") from exc
    return ParsedTable(
        header=[],
        rows=[[cell.strip() for cell in row] for row in rows],
        source_format="csv",
        delimiter=delimiter,
        encoding=encoding,
    )


# --------------------------------------------------------------------------- #
# Excel
# --------------------------------------------------------------------------- #
def _vet_zip(raw: bytes) -> None:
    """Vet the workbook's **central directory** before a byte of it is decompressed.

    ``ZipFile`` reads only the directory at construction, so every size below is the archive's
    own declaration — which is all a decompression bomb has to lie about, and all we need to
    catch it. Measuring the real inflated size would mean inflating it, which *is* the attack.
    """
    try:
        with zipfile.ZipFile(io.BytesIO(raw)) as archive:
            infos = archive.infolist()
    except zipfile.BadZipFile as exc:
        raise AppError("invalid_xlsx", "impex.errors.invalid_xlsx") from exc

    if len(infos) > MAX_XLSX_MEMBERS:
        raise AppError("invalid_xlsx", "impex.errors.invalid_xlsx")
    total = 0
    for info in infos:
        total += info.file_size
        ratio = info.file_size / max(info.compress_size, 1)
        if ratio > MAX_XLSX_RATIO or total > MAX_XLSX_INFLATED_BYTES:
            raise AppError(
                "file_too_large", "impex.errors.file_too_large", status_code=413
            )


def _xlsx_cell(value: Any) -> str:
    """One Excel cell → the string the rest of the engine coerces.

    Excel has no text/number distinction the way a CSV does: a postcode is a number, a date is
    a float with a format, and ``str()`` on either produces something the column's own coercion
    would then reject. So the shapes that have a canonical text form get one here — ISO for
    dates and times, no exponent and no trailing ``.0`` for numbers — and everything else is
    left to the column.
    """
    if value is None:
        return ""
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, datetime):
        # A date-only cell arrives as midnight; writing "2026-01-05 00:00:00" into a date
        # column would fail its own ISO check.
        return (
            value.date().isoformat()
            if value.time() == time(0, 0)
            else value.isoformat(sep=" ", timespec="minutes")
        )
    if isinstance(value, (date, time)):
        return value.isoformat()
    if isinstance(value, float):
        # 1234.0 is what Excel stores for an integer; "1234.0" is not a client number.
        return str(Decimal(str(value)).normalize())
    return str(value).strip()


def _parse_xlsx(raw: bytes, *, sheet: str | None) -> ParsedTable:
    try:
        from openpyxl import load_workbook
    except ModuleNotFoundError as exc:  # pragma: no cover — dependency is declared
        raise AppError("invalid_xlsx", "impex.errors.invalid_xlsx") from exc

    _vet_zip(raw)
    try:
        workbook = load_workbook(
            io.BytesIO(raw), read_only=True, data_only=True, keep_links=False
        )
    except AppError:
        raise
    except Exception as exc:  # openpyxl raises a zoo of types on a malformed workbook
        raise AppError("invalid_xlsx", "impex.errors.invalid_xlsx") from exc

    try:
        sheets = tuple(workbook.sheetnames)
        if sheet is not None and sheet not in sheets:
            raise AppError("sheet_not_found", "impex.errors.sheet_not_found")
        name = sheet or (sheets[0] if sheets else "")
        if not name:
            raise AppError("empty_file", "impex.errors.empty_file")
        rows = _read_sheet(workbook[name])
    finally:
        workbook.close()

    return ParsedTable(
        header=[],
        rows=rows,
        source_format="xlsx",
        sheet=name,
        sheets=sheets,
        uncalculated_formulas=_count_uncalculated(raw, name, rows),
    )


def _read_sheet(worksheet: Any) -> list[list[str]]:
    """Rows of one worksheet, capped in both directions **while** reading.

    ``max_col`` bounds the read itself rather than trimming afterwards: a sheet whose
    ``max_column`` is 16 384 would otherwise allocate 16 384 cells per row before we could
    object to the width.
    """
    rows: list[list[str]] = []
    for raw_row in worksheet.iter_rows(max_col=MAX_COLUMNS + 1, values_only=True):
        cells = [_xlsx_cell(value) for value in raw_row]
        while cells and cells[-1] == "":
            cells.pop()  # trailing formatted-but-empty cells are not columns
        if not cells:
            continue  # a wholly empty row, as the delimited path also skips
        if len(cells) > MAX_COLUMNS:
            raise AppError("too_many_columns", "impex.errors.too_many_columns")
        rows.append(cells)
        if len(rows) > MAX_IMPORT_ROWS + 1:
            # +1 for the header; the caller turns this into the row-count error, so stop
            # reading rather than materialising a file we are going to refuse.
            break
    return rows


def _count_uncalculated(raw: bytes, sheet: str, parsed: list[list[str]]) -> int:
    """How many cells hold a formula whose cached result is missing.

    Needs a second pass because the two facts live in different reads: ``data_only=True``
    returns the cached value (``None`` when there is none) and ``data_only=False`` returns the
    formula text. Only run when the first pass actually produced blanks, so a fully populated
    sheet — the common case — pays nothing. A **short** row counts as blank: the read trims
    trailing empties, so the missing cells are exactly the ones that never came back.
    """
    width = max((len(row) for row in parsed), default=0)
    if not any(len(row) < width or "" in row for row in parsed):
        return 0
    try:
        from openpyxl import load_workbook

        workbook = load_workbook(
            io.BytesIO(raw), read_only=True, data_only=False, keep_links=False
        )
    except Exception:  # noqa: BLE001 — a warning we cannot compute is not an import failure
        return 0
    try:
        if sheet not in workbook.sheetnames:
            return 0
        count = 0
        for index, raw_row in enumerate(
            workbook[sheet].iter_rows(max_col=MAX_COLUMNS + 1, values_only=True)
        ):
            if index >= len(parsed):
                break
            for position, value in enumerate(raw_row):
                blank = position >= len(parsed[index]) or parsed[index][position] == ""
                if blank and isinstance(value, str) and value.startswith("="):
                    count += 1
        return count
    finally:
        workbook.close()


# --------------------------------------------------------------------------- #
# Shared tail
# --------------------------------------------------------------------------- #
def _finish(table: ParsedTable, *, has_header: bool) -> ParsedTable:
    """Split the header off, apply the row and column caps, pad the rows to one width.

    Padding here rather than at every read site is what lets the mapping step address a column
    by index without every consumer re-checking the row's length: column 7 of a row that ended
    at column 4 is an empty cell, not an ``IndexError``.
    """
    rows = table.rows
    if not rows:
        raise AppError("empty_file", "impex.errors.empty_file")

    header = [cell.strip() for cell in rows[0]] if has_header else []
    data = rows[1:] if has_header else rows
    if not data:
        raise AppError("empty_file", "impex.errors.empty_file")
    if len(data) > MAX_IMPORT_ROWS:
        raise AppError("too_many_rows", "impex.errors.too_many_rows", status_code=413)

    width = max([len(header), *(len(row) for row in data)], default=0)
    if width > MAX_COLUMNS:
        raise AppError("too_many_columns", "impex.errors.too_many_columns")
    if has_header:
        header = header + [""] * (width - len(header))
    padded = [row + [""] * (width - len(row)) for row in data]

    return ParsedTable(
        header=header,
        rows=padded,
        source_format=table.source_format,
        delimiter=table.delimiter,
        encoding=table.encoding,
        sheet=table.sheet,
        sheets=table.sheets,
        uncalculated_formulas=table.uncalculated_formulas,
    )
