"""customfields_create_definitions

Revision ID: ed3e9e4cd88d
Revises: a4fb5ebe1dc8
Create Date: 2026-07-07 12:30:52.145309
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = 'ed3e9e4cd88d'
down_revision: str | None = 'a4fb5ebe1dc8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_custom_field_definitions_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_definitions')),
    sa.UniqueConstraint('org_id', 'entity_type', 'key', name='uq_custom_field_org_entity_key')
    )
    op.create_index(op.f('ix_custom_field_definitions_entity_type'), 'custom_field_definitions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_org_id'), 'custom_field_definitions', ['org_id'], unique=False)
    # ### end Alembic commands ###

    # Tenant isolation (defence-in-depth): definitions are org-scoped, RLS-forced (CLAUDE.md §13).
    enable_rls("custom_field_definitions")


def downgrade() -> None:
    disable_rls("custom_field_definitions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_field_definitions_org_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_entity_type'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
